# This workflow builds and pushes a Docker image to Docker Hub

name: CI - Build and Push Docker Image

# This workflow runs on any push to the "main" branch
on:
  push:
    branches: ["main"]

# Defines the single job in this workflow
jobs:
  build-and-push:
    # The job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # These are the steps the job will execute
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using your secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the Docker image with your username and project name
      - name: Build the Docker image
        run: docker build -t mayanksdhamii/webstatus-checker:latest .

      # Step 4: Push the built image to your Docker Hub repository
      - name: Push the Docker image to Docker Hub
        run: docker push mayanksdhamii/webstatus-checker:latest
